### ISSUE TITLE
WARNING Mage_OAuth.csv

### ISSUE THREAD

**Issue by Elfen-Service** [MaWoScha/German_LocalePack_es_ES#1]
Hello, i think its the same issue as in German_LocalePack_de_DE (typo):

WARNING: Target does not exist (.modman/German_LocalePack_es_ES/modman):
 app/locale/es_ES/Mage_OAuth.csv app/locale/es_ES/Mage_OAuth.csv

Thanks for your work!

**Comment by MaWoScha** [comment]
Is fixed! Thank you for reporting!
MaWoScha
